"""
This repository saves new residents to SQLite and fetches them by ID, 
converting database rows back into Python objects.
"""
import sqlite3
from typing import Optional # So when an ID is not found, it'll just return None
from src.csms.models.resident import Resident


class ResidentRepository:

    def __init__(self, db_path: str = "csms.db"):
        # Store the path to the SQLite database file
        self.db_path = db_path

    def _get_connection(self) -> sqlite3.Connection:
        # a method to get a database connection that returns rows as objects
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row # access columns by name
        return conn

    def save(self, resident: Resident) -> Resident:
        # stores a valid Resident in SQLite and attaches the generated ID.
        conn = self._get_connection()
        cursor = conn.cursor()

        # insert resident attributes into the database
        cursor.execute(
            """
            INSERT INTO residents (first_name, last_name, address, contact_number, email, status)
            VALUES (?, ?, ?, ?, ?, ?)
        """,
            (
                resident.first_name,
                resident.last_name,
                resident.address,
                resident.contact_number,
                resident.email,
                resident.status,
            ),
        )

        # Commit insert transaction
        conn.commit()

        # IDs that auto increments, generated by SQLite and attach it to the resident object
        resident.id = cursor.lastrowid # grab the newly generated id
        conn.close()

        return resident

    def find_by_id(self, resident_id: int) -> Optional[Resident]:
        # Retrieves a Resident from SQLite using their ID, returning None if missing.
        conn = self._get_connection()
        cursor = conn.cursor()

        # Fetch matching record by primary key
        cursor.execute(
            """
            SELECT id, first_name, last_name, address, contact_number, email, status
            FROM residents
            WHERE id = ?
        """,
            (resident_id,),
        )

        row = cursor.fetchone()
        conn.close()

        # not-found handling, which return None if ID does not exist in SQLite
        if row is None:
            return None

        # Reconstruct and return a proper Resident object from database row columns
        return Resident(
            id=row["id"],
            first_name=row["first_name"],
            last_name=row["last_name"],
            address=row["address"],
            contact_number=row["contact_number"],
            email=row["email"],
            status=row["status"],
        )