"""
# T03: This repository saves new residents to SQLite, fetches them by ID,
lists all residents, and searches residents by name, converting database rows back into Python objects.

# Ticket T05 and T06: Extensions Included

"""
import sqlite3
from typing import Optional  # So when an ID is not found, it'll just return None
from src.csms.models.resident import Resident


class ResidentRepository:

    def __init__(self, db_path: str = "csms.db"):
        # Store the path to the SQLite database file
        self.db_path = db_path

    def _get_connection(self) -> sqlite3.Connection:
        # a method to get a database connection that returns rows as objects
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row  # access columns by name
        return conn

    # --- Ticket T05: Helper Method for Mapping Rows ---
    def _map_row_to_resident(self, row: sqlite3.Row) -> Resident:
        """Ticket T05: Reconstructs a Resident object from a database row."""
        return Resident(
            id=row["id"],
            first_name=row["first_name"],
            last_name=row["last_name"],
            address=row["address"],
            contact_number=row["contact_number"],
            email=row["email"],
            status=row["status"],
        )

    def save(self, resident: Resident) -> Resident:
        # stores a valid Resident in SQLite and attaches the generated ID.
        conn = self._get_connection()
        cursor = conn.cursor()

        # insert resident attributes into the database
        cursor.execute(
            """
            INSERT INTO residents (first_name, last_name, address, contact_number, email, status)
            VALUES (?, ?, ?, ?, ?, ?)
        """,
            (
                resident.first_name,
                resident.last_name,
                resident.address,
                resident.contact_number,
                resident.email,
                resident.status,
            ),
        )

        # Commit insert 
        conn.commit()

        # IDs that auto increments, generated by SQLite and attach it to the resident object
        resident.id = cursor.lastrowid  # grab the newly generated id
        conn.close()

        return resident

    def find_by_id(self, resident_id: int) -> Optional[Resident]:
        # Retrieves a Resident from SQLite using their ID, returning None if missing.
        conn = self._get_connection()
        cursor = conn.cursor()

        # Fetch matching record by primary key
        cursor.execute(
            """
            SELECT id, first_name, last_name, address, contact_number, email, status
            FROM residents
            WHERE id = ?
        """,
            (resident_id,),
        )

        row = cursor.fetchone()
        conn.close()

        # not-found handling, which return None if ID does not exist in SQLite
        if row is None:
            return None

        # Ticket T05 Refactor: the row mapping helper
        return self._map_row_to_resident(row)

    # --- Ticket T05: Find All Persisted Residents ---
    def find_all(self) -> list[Resident]:
        """Ticket T05: Retrieves all persisted residents ordered by last_name, first_name, and id."""
        conn = self._get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT id, first_name, last_name, address, contact_number, email, status
            FROM residents
            ORDER BY
                LOWER(last_name) ASC,
                LOWER(first_name) ASC,
                id ASC
        """
        )

        rows = cursor.fetchall()
        conn.close()

        return [self._map_row_to_resident(row) for row in rows]

    # --- Ticket T05: Search Residents By Name ---
    def search_by_name(self, search_term: str) -> list[Resident]:
        """Ticket T05: Case-insensitive partial search by first name or last name."""
        conn = self._get_connection()
        cursor = conn.cursor()

        pattern = f"%{search_term}%"

        cursor.execute(
            """
            SELECT id, first_name, last_name, address, contact_number, email, status
            FROM residents
            WHERE
                LOWER(first_name) LIKE LOWER(?)
                OR LOWER(last_name) LIKE LOWER(?)
            ORDER BY
                LOWER(last_name) ASC,
                LOWER(first_name) ASC,
                id ASC
        """,
            (pattern, pattern),
        )

        rows = cursor.fetchall()
        conn.close()

        return [self._map_row_to_resident(row) for row in rows]

    # --- Ticket T06: Update Existing Resident ---
    def update(self, resident: Resident) -> Optional[Resident]:
        """T06: Updates editable fields of an existing resident in SQLite by ID."""
        # cannot update if ID is missing
        if resident.id is None:
            return None

        conn = self._get_connection()
        cursor = conn.cursor()

        # Execute UPDATE query - preserving id and status
        cursor.execute(
            """
            UPDATE residents
            SET first_name = ?,
                last_name = ?,
                address = ?,
                contact_number = ?,
                email = ?,
                status = ?
            WHERE id = ?
        """,
            (
                resident.first_name,
                resident.last_name,
                resident.address,
                resident.contact_number,
                resident.email,
                resident.status,
                resident.id,
            ),
        )

        conn.commit()
        rows_affected = cursor.rowcount
        conn.close()

        # If no row matched the ID, return None (not found)
        if rows_affected == 0:
            return None

        return resident